### PR TITLE
Implemented shortlink input with '_' separator and multiple copy using ","

### LINKED ISSUE #8: Validate new shortlink input (for save)
When new shortlinks are added, make sure to remove any spaces or commas and replace them with `_`. 
  - Eg: `foo, bar ,` is saved as `foo_bar` (commas and spaces are replaced w/ underscores, then remove multiple underscores).

### PR DESCRIPTION
**Pull request by amitx13**
new shortlinks are added with removed spaces or commas and replace them with `_`
`Eg: foo, bar , `is saved as `foo_bar` (commas and spaces are replaced w/ underscores, then remove multiple underscores).

Extend the copy/c command such that you can pass in multiple arguments that are comma delimited. These should all be copied to the clipboard & joined w/ \n.
`Eg: copy foo_bar,baz`

### CODE REVIEW

**Comment by nazmulidris** [comment]
@amitx13 Thank you for spending your time on this PR. Unfortunately I can't accept it as is. Here are a few things to note, it is desirable to:
1) run the code through prettier to format it consistently w/ the rest of the code base
2) have functions that encapsulate the logic cleanly
3) have tests for the functions added above
4) refactor all the code after writing it for the best readability.

**Comment by nazmulidris** [comment]
@amitx13 Thank you for spending time on this. Even though we didn't accept your PR, we added `hacktoberfest-accepted` label to it, so you should get credit for it.

**Comment by amitx13** [comment]
@nazmulidris thank you sir for your feedback  and support I will not make these mistake again

**Comment by nazmulidris** [comment]
@amitx13 No need to apologize. Thank you so much for taking the time to contribute. This is a long journey and there are lots of things to learn.

**Pull request closed without merging**
